// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorningStartApi.Data;

#nullable disable

namespace MorningStartApi.Migrations
{
    [DbContext(typeof(SistemaMercadoriasDBContex))]
    [Migration("20231023140235_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MorningStartApi.Models.EstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Local")
                        .HasColumnType("longtext");

                    b.Property<int?>("MercadoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Operacao")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MercadoriaId");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("MorningStartApi.Models.MercadoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroDeRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mercadoria");
                });

            modelBuilder.Entity("MorningStartApi.Models.EstoqueModel", b =>
                {
                    b.HasOne("MorningStartApi.Models.MercadoriaModel", "Mercadoria")
                        .WithMany()
                        .HasForeignKey("MercadoriaId");

                    b.Navigation("Mercadoria");
                });
#pragma warning restore 612, 618
        }
    }
}
